@startuml DisciplinaDeAnalisisDiagramaDePaquetes
left to right direction

package "Gestion de curso de extension" as G_cursoExtension{
    object CursoDeExtension
} 

package "Gestion de propuesta" as G_propuesta{
    object RegistrarRecaudos
    object CargarFormulacionDelCursoDeExtension
    object PresentarCronogramaDeEjecucion
    object PresentarEstructuraDeCostosEIngreso
}

package "Gestion de aval" as G_aval{
    object EvaluarInformacionConsignada
    object ResponderEvaluacionDeAval
    object GenerarCartaDeCompromiso
    object FirmarCartaDeIntencion
}

G_aval --> G_cursoExtension #Black;line.dashed;
G_propuesta --> G_cursoExtension #Black;line.dashed;

package "Gestion de usuario proponente" as G_userProponente{
    object VerExpediente
    object VerCursoPropusto
    object VerEstadoDeAval
}

package "Gestion de usuario" as G_user {
    object Registrarse
    object IniciarSesion
    object CerrarSesion
    object VerDashboard
}
G_userProponente --> G_propuesta #Black;line.dashed;
G_aval --> G_user #Black;line.dashed;
G_userProponente ----> G_user #Black;line.dashed;
G_propuesta ------> G_user #Black;line.dashed;

@enduml