@startuml DisciplinaDeRequisitosDiagramaDeEstadoRelacionAdministrador
title Administrador

[*] --> UsuarioIniciado : iniciar sesión
UsuarioIniciado --> ViendoDashboardAdministrador : ver dashboard
ViendoDashboardAdministrador --> ViendoCursos : ver cursos
ViendoCursos --> RespondiendoEvaluacionDeAval : responder evaluación de aval
RespondiendoEvaluacionDeAval --> ViendoDashboardAdministrador : regresar
ViendoCursos --> GenerandoCartaDeIntencion : generar carta de intención
GenerandoCartaDeIntencion --> ViendoDashboardAdministrador : regresar
ViendoCursos --> GenerandoCartaDeCompromiso : generar carta de compromiso
GenerandoCartaDeCompromiso --> ViendoDashboardAdministrador : regresar
ViendoDashboardAdministrador ---> CerrandoSesion : cerrar sesión 
CerrandoSesion --> [*]

@enduml