@startuml DisciplinaDeRequisitosDiagramaDeEstadoRelacionProponente
title Proponente

[*] --> UsuarioIniciado : iniciar sesión
UsuarioIniciado --> ViendoDashboardProponente : ver dashboard
ViendoDashboardProponente --> ViendoExpediente : ver expediente
ViendoExpediente --> ViendoDashboardProponente : regresar
ViendoDashboardProponente ---> ViendoCursos : ver cursos propuestos
ViendoCursos --> ViendoEstadoDelAval : ver estado del aval
ViendoCursos -> ViendoDashboardProponente : regresar
ViendoDashboardProponente ---> RecaudosRegistrados : registrar recaudos
RecaudosRegistrados --> FormulacionDelCursoCargada : cargar formulación del curso
FormulacionDelCursoCargada --> ViendoDashboardProponente : regresar
ViendoDashboardProponente  ---> SesionCerrada : cerrar sesión 
SesionCerrada --> [*]

@enduml