@startuml DisciplinaDeAnalisisDiagramaDeClaseVerExpediente
actor "Proponente" as actorProponente

entity "Expediente" as entidadExpediente
entity "Carta de intencion" as entidadCartaDeIntencion
entity "Carta de compromiso" as entidadCartaDeCompromiso


boundary "Vista de expediente" as vistaExpediente

control "Gestor de infomacion del expediente" as ctrlGestorExpediente
control "Gestor de carta de intencion" as ctrlGestorCartaDeIntencion
control "Gestor de carta de compromiso" as ctrlGestorCartaDeCompromiso


actorProponente -- vistaExpediente
vistaExpediente -- ctrlGestorInformacionExpediente
ctrlGestorInformacionExpediente -- entidadExpediente

@enduml