@startuml DisciplinaDeAnalisisDiagramaDeClaseResponderEvaluacion
left to right direction

actor "Administrador" as actorAdmin

entity "Propuesta" as entidadPropuesta
entity "Aval tecnico" as entidadAval

boundary "Vista de evaluacion de aval" as vistaEvaluacion

control "Gestor de evaluacion" as ctrlGestorEvaluacion

actorAdmin -- vistaEvaluacion
vistaEvaluacion -- ctrlGestorEvaluacion
ctrlGestorEvaluacion -- entidadPropuesta
entidadPropuesta -- entidadAval
ctrlGestorEvaluacion -- entidadAval

@enduml