@startuml DisciplinaDeAnalisisDiagramaDeClaseGenerarCartaCompromiso
left to right direction

actor "Administrador" as actorAdmin
actor "Aliado" as actorAliado


entity "Propuesta" as entidadPropuesta
entity "Aval tecnico" as entidadAval
entity "Expediente" as entidadExpediente
entity "Carta de compromiso" as entidadCartaCompromiso

boundary "Vista de propuestas" as vistaPropuestas
boundary "Vista de generar carta de compromiso" as vistaGenerarCartaDeCompromiso
boundary "Vista de ingresar informacion" as vistaIngresarInformacion
boundary "Vista de revision de la carta" as vistaRevisionCartaDeCompromiso


control "Gestor de carta de compromiso" as ctrlGestorCartaCompromiso

actorAdmin -- vistaPropuestas
vistaPropuestas -- entidadPropuesta
vistaPropuestas -- vistaGenerarCartaDeCompromiso
vistaGenerarCartaDeCompromiso -- ctrlGestorCartaCompromiso

vistaGenerarCartaDeCompromiso -- vistaIngresarInformacion
ctrlGestorCartaCompromiso -- entidadCartaCompromiso 
entidadCartaCompromiso -- entidadExpediente
ctrlGestorCartaCompromiso -- entidadAval

actorAliado -- vistaRevisionCartaDeCompromiso
vistaRevisionCartaDeCompromiso -- ctrlGestorCartaCompromiso
@enduml
