@startuml DisciplinaDeAnalisisDiagramaDeClaseAnalisisVerExpediente
actor "Proponente" as actorProponente
actor "Aliado" as actorAliado

entity "Expediente del aliado" as entidadExpediente

boundary "Vista ver expediente del aliado" as vistaVerExpediente

control "Gestor de infomacion del expediente" as ctrlGestorInformacionExpediente

actorProponente -- vistaVerExpediente
actorAliado -- vistaVerExpediente
vistaVerExpediente -- ctrlGestorInformacionExpediente
ctrlGestorInformacionExpediente -- entidadExpediente

@enduml