@startuml DisciplinaDeAnalisisDiagramaDeClasePresentarCronograma
left to right direction

actor "Aliado" as actorAliado

entity "Cronograma de ejecucion" as entidadCronogramaEjecucion
entity "Curso de extension" as entidadCursoExtension


boundary "Vista de presentacion cronograma" as vistaPresentacionCronograma

control "Gestor de cronograma" as ctrlGestorCronograma

actorAliado -- vistaPresentacionCronograma
vistaPresentacionCronograma -- ctrlGestorCronograma
ctrlGestorCronograma -- entidadCronogramaEjecucion
entidadCursoExtension -- entidadCronogramaEjecucion

' Aliado -> IU : Ingresar cronograma
' IU -> MGC : Validar cronograma
' MGC -> BD : Guardar cronograma
' BD -> MGC : Confirmar almacenamiento
' MGC -> IU : Notificar éxito
' IU -> Aliado : Mostrar confirmación
@enduml