@startuml DisciplinaDeAnalisisDiagramaDePaquetes
left to right direction

package "gestionDeCursoDeExtension" as G_cursoExtension{
    object CursoDeExtension
} 

package "gestionDePropuesta" as G_propuesta{
    object RegistrarRecaudos
    object CargarFormulacionDelCursoDeExtension
    object PresentarCronogramaDeEjecucion
    object PresentarEstructuraDeCostosEIngreso
}

package "gestionDeAval" as G_aval{
    object EvaluarInformacionConsignada
    object ResponderEvaluacionDeAval
    object GenerarCartaDeCompromiso
    object FirmarCartaDeIntencion
}

G_aval --> G_cursoExtension #Black;line.dashed;
G_propuesta --> G_cursoExtension #Black;line.dashed;

package "GestionDeCursosPropuestos" as G_userProponente{
    object VerCursosPropuestos
    object VerEstadoDeAval
    object VerExpediente
}

package "gestionSesionUsuario" as G_user {
    object Registrarse
    object IniciarSesion
    object CerrarSesion
    object VerDashboard
}
G_userProponente --> G_propuesta #Black;line.dashed;
G_aval --> G_user #Black;line.dashed;
G_userProponente ----> G_user #Black;line.dashed;
G_propuesta ------> G_user #Black;line.dashed;

@enduml