@startuml DisciplinaDeAnalisisDiagramaDeColaboracionRegistrarse
left to right direction

actor ":Usuario" as actorUsuario

entity ":Sesion usuario" as entidadSesionUsuario

boundary ":Formulario de registro" as vistaRegistrarse
boundary ":Vista de dashboard" as vistaDashboard

control ":Gestor de sesion de usuario" as ctrlGestorSesion

actorUsuario -- vistaRegistrarse : ""-->""\n//1:registrarse()//\n""-->""\n//2:ingresarDatos()//
vistaRegistrarse -- ctrlGestorSesion : ""-->""\n//3:esDatosCompletos()//\n""-->""\n//4:enviarDatos()//\n""<--""\n//7:esExitosa()//
ctrlGestorSesion -- entidadSesionUsuario : ""-->""\n//5:crearUsuario()//\n""<--""\n//6:esExitosa()//

vistaRegistrarse -- vistaDashboard : ""-->""\n//8:mostrarDashboard()//

@enduml