@startuml DisciplinaDeAnalisisDiagramaDeClaseRegistrarse

left to right direction

actor "Usuario" as actorUsuario

entity "Sesion usuario" as entidadSesionUsuario

boundary "Formulario de registro" as vistaRegistrarse
boundary "Formulario de inicio sesion" as vistaInicioSesion
boundary "Vista de dashboard" as vistaDashboard

control "Gestor de sesion de usuario" as ctrlGestorSesion

actorUsuario -- vistaRegistrarse
vistaRegistrarse -- ctrlGestorSesion
ctrlGestorSesion -- entidadSesionUsuario

vistaRegistrarse -- vistaDashboard

@enduml