@startuml DisciplinaDeAnalisisDiagramaDeClaseResponderEvaluacion
actor "Administrador" as actorAdmin

entity "Aval tecnico" as entidadAval
entity "Propuesta" as entidadPropuesta

boundary "Vista de evaluacion de aval" as vistaRespuestaEvaluacion

control "Gestor de evaluacion" as ctrlGestorEvaluacion
control "Gestor de observaciones" as ctrlGestorObservaciones

actorAdmin -- vistaRespuestaEvaluacion
vistaRespuestaEvaluacion -- ctrlGestorEvaluacion
ctrlGestorEvaluacion -- entidadPropuesta
ctrlGestorEvaluacion -- entidadAval
vistaRespuestaEvaluacion -- ctrlGestorObservaciones
ctrlGestorObservaciones -- entidadAval

@enduml