@startuml DiagramaDeColaboracionResponderEvaluacionAval
left to right direction

actor "Administrador" as actorAdmin

entity "Propuesta" as entidadPropuesta
entity "Aval tecnico" as entidadAval

boundary "Vista de evaluacion" as vistaEvaluacion
boundary "Vista de informacion consignada" as vistaInfoConsignada
boundary "Vista de observaciones" as vistaObservaciones

control "Gestor de evaluacion" as ctrlGestorEvaluacion

actorAdmin -- vistaEvaluacion : ""-->""\n//1:verPropuesta()//\n""<--""\n//4:mostrarInfoPropuesta()//\n""-->""\n//5:evaluarAval()//
vistaEvaluacion -- vistaInfoConsignada
vistaEvaluacion -- vistaObservaciones

vistaInfoConsignada -- entidadPropuesta : ""-->""\n//2:obtenerInfoPropuesta()//\n""<--""\n//3:devolverInfoPropuesta()//

vistaEvaluacion -- ctrlGestorEvaluacion : ""-->""\n//6:enviarEvaluacion()//
ctrlGestorEvaluacion -- entidadAval : ""-->""\n//7:guardar()//

@enduml