@startuml DisciplinaDeAnalisisDiagramaDeColaboracionVerCursos
left to right direction

actor "Proponente" as actorProponente

entity "Curso" as entidadCurso
entity "Propuesta" as entidadPropuesta

boundary "Vista de cursos propuestos" as vistaCursosPropuestos

control "Gestor de informacion de cursos" as ctrlGestorInformacionCursos

actorProponente -- vistaCursosPropuestos : ""-->""\n//1:verCursos()//\n""<--""\n//8:mostrarCursos()//
vistaCursosPropuestos -- ctrlGestorInformacionCursos : ""-->""\n//2:obtenerCursos()//\n""<--""\n//7:devolverCursos()//
ctrlGestorInformacionCursos -- entidadCurso : ""-->""\n//3:obtenerCursos()//\n""<--""\n//6:devolverCursos()//
entidadCurso -- entidadPropuesta : ""-->""\n//4:obtenerEstadoAval()//\n""<--""\n//5:devolverEstado()//

@enduml