@startuml ModeloDeDominioDiagramaDeEstado
[*] --> ProponenteEnRegistro

state ProponenteEnRegistro {
    [*] --> DatosRegistrados : registrar datos

    state EsPersonaNatural <<choice>>
    DatosRegistrados --> EsPersonaNatural : es persona natural?
    EsPersonaNatural --> PersonaNaturalEnRegistro : Sí
    EsPersonaNatural --> PersonaJuridicaEnRegistro : No
    PersonaNaturalEnRegistro --> RecaudosConsignados : consignar recaudos
    PersonaJuridicaEnRegistro --> RecaudosConsignados : consignar recaudos
    RecaudosConsignados --> [*]
}

ProponenteEnRegistro --> ProponenteRegistrado
ProponenteRegistrado --> PropuestaEnFormulacion : iniciar formulacion

state PropuestaEnFormulacion {
    [*] --> DetallesIngresados : ingresar detalles de propuesta
    DetallesIngresados --> [*]
}

PropuestaEnFormulacion --> PropuestaFormulada
PropuestaFormulada --> PropuestaEnEvaluacion : iniciar evaluacion

note right
    Se entiende que las evaluaciones pueden ser concurrentes
end note
state PropuestaEnEvaluacion {
    state EsDiplomado <<choice>>
    [*] --> EnEvaluacionCoordinacionDeExtension
    EnEvaluacionCoordinacionDeExtension --> EsDiplomado : es diplomado?
    EsDiplomado --> EnEvaluacionConsejoDeFacultad : Sí
    EsDiplomado --> EnEvaluacionComisionDeFacultad : No
    EnEvaluacionConsejoDeFacultad --> EvaluadaPorCoordinacionDeExtension : evaluar
    EnEvaluacionComisionDeFacultad --> EvaluadaPorCoordinacionDeExtension : evaluar

    --

    [*] --> EnEvaluacionDEU : delegar
    EnEvaluacionDEU --> EvaluadaPorDEU : evaluar
    
}

PropuestaEnEvaluacion --> PropuestaEvaluada
PropuestaEvaluada --> ObtencionDeResultado
state ObtencionDeResultado {
    state AvalTecnicoEsAprobado <<choice>>
    [*] --> AvalTecnicoEsAprobado : aval tecnico aprobado?
    AvalTecnicoEsAprobado --> AvalTecnicoNoAprobado : No
    AvalTecnicoEsAprobado --> AvalTecnicoAprobado : Sí
    
}

state AvalTecnicoAprobado {
    [*] --> CartaDeIntencionGenerada : generar carta de intencion
    CartaDeIntencionGenerada --> ProponenteAliado : cambiar status de proponente

    ProponenteAliado --> CronogramaPresentado : presentar cronograma de ejecucion
    CronogramaPresentado --> EstructuraDeCostosPresentada : presentar estructura de costos 
    note right
        Se entiende que son secuenciales tacitamente 
    end note
    EstructuraDeCostosPresentada --> CartaDeCompromisoGenerada : generar carta de compromiso
    CartaDeCompromisoGenerada --> CartaDeCompromisoFirmada : firmar
    CartaDeCompromisoFirmada --> [*]
}

AvalTecnicoAprobado --> [*]
AvalTecnicoNoAprobado --> [*]
@enduml