@startuml DiagramaDeSecuenciaIniciarSesion
skinparam sequenceParticipant underline

actor Usuario as user
boundary ":Formulario de inicio de sesión" as FIS
control ":Gestor de sesión" as GS
entity ":Sesión de usuario" as SU
boundary ":Vista de dashboard" as VD


user -> FIS : iniciarSesion()
activate FIS
user -> FIS : IngresarDatos()
FIS -> GS : enviarDatos()
deactivate FIS
activate GS
GS -> SU : verficarDatos()
activate SU
SU -> SU : esCorrecto()
SU -> SU : actualizarHoraDeInicio()
SU --> GS : responderValidacion()
deactivate SU
GS -> VD : mostrarDashboard()
deactivate GS
activate VD
deactivate VD

@enduml
