@startuml DiagramaDeSecuenciaRegistrarse
skinparam sequenceParticipant underline

actor Usuario
participant ":VistaFormularioRegistro" as VistaFormularioRegistro
participant ":GestorSesionUsuario" as GestorSesionUsuario
participant ":SesionUsuario" as SesionUsuario
participant ":VistaDashboard" as VistaDashboard
participant ":VistaError" as VistaError


Usuario -> VistaFormularioRegistro : 1:registrarse()
activate VistaFormularioRegistro
Usuario -> VistaFormularioRegistro : 2:ingresarDatos()
VistaFormularioRegistro -> VistaFormularioRegistro : 3:esDatosCompletos()
alt False
VistaFormularioRegistro --> VistaError: 4:mostrarError()
end
VistaFormularioRegistro -> GestorSesionUsuario : 4:registrarse(datos)
deactivate VistaFormularioRegistro
activate GestorSesionUsuario
GestorSesionUsuario -> SesionUsuario : 5:registrarUsuario(datos)
activate SesionUsuario
SesionUsuario -> SesionUsuario : 6:crearUsuario(datos)
SesionUsuario -> SesionUsuario : 7:actualizarHoraDeInicio()
deactivate SesionUsuario
GestorSesionUsuario -> VistaDashboard : 8:mostrarDashboard()
deactivate GestorSesionUsuario
activate VistaDashboard
deactivate VistaDashboard


@enduml