@startuml DiagramaDeDespliegue

node "Cliente" {
  node "Usuario" {
  }
  node "Administrador" {
  }
}

node "Servidor Web" {
  
}

node "Servidor de Aplicaciones" {
  node "gestionDeCartasDePropuesta" {
    ' [GenerarCartaDeCompromiso]
    ' [FirmarCartaDeIntencion]
  }
  
  node "gestionDeProcesoPropuesta" {
    ' [RegistrarRecaudos]
    ' [CargarFormulacionDelCursoDeExtension]
  }

  node "gestionDeAval" {
    ' [EvaluarInformacionConsignada]
    ' [ResponderEvaluacionDeAval]
  }

  node "gestionDeSesionUsuario" {
    ' [IniciarSesion]
    ' [Registrarse]
    ' [VerDashboard]
    ' [CerrarSesion]
  }

  node "gestionDePresentacionesDeCurso" {
    ' [PresentarCronogramaDeEjecucion]
    ' [PresentarEstructuraDeCostosEIngreso]
  }

  node "gestionDeCursosPropuestos" {
    ' [VerEstadoDeAval]
    ' [VerCursosPropuestos]
    ' [VerExpediente]
  }
}

node "Base de Datos" {
  node "CourseManagerUCV" {
  }
}
[Cliente] -- [Servidor Web]
[Servidor Web] -d-- [Servidor de Aplicaciones] : HTTP
[Servidor de Aplicaciones] -d-- [Base de Datos]

@enduml