@startuml DiagramaDeSecuenciaIniciarSesion
skinparam sequenceParticipant underline

actor Usuario as user
boundary VistaFormularioInicioSesion
control GestorSesionUsuario
entity SesionUsuario
boundary VistaDashboard


user -> VistaFormularioInicioSesion : iniciarSesion()
activate VistaFormularioInicioSesion
user -> VistaFormularioInicioSesion : IngresarDatos()
VistaFormularioInicioSesion -> GestorSesionUsuario : enviarDatos()
deactivate VistaFormularioInicioSesion
activate GestorSesionUsuario
GestorSesionUsuario -> SesionUsuario : verficarDatos()
activate SesionUsuario
SesionUsuario -> SesionUsuario : esCorrecto()
SesionUsuario -> SesionUsuario : actualizarHoraDeInicio()
SesionUsuario --> GestorSesionUsuario : responderValidacion()
deactivate SesionUsuario
GestorSesionUsuario -> VistaDashboard : mostrarDashboard()
deactivate GestorSesionUsuario
activate VistaDashboard
deactivate VistaDashboard

@enduml
