@startuml DiagramaDeSecuenciaCerrarSesion
skinparam sequenceParticipant underline

actor Usuario as user
boundary VistaOpcionCerrarSesion
control GestorSesionUsuario
entity SesionUsuario
boundary VistaFormularioInicioSesion


user -> VistaOpcionCerrarSesion : cerrarSesion()
activate VistaOpcionCerrarSesion
VistaOpcionCerrarSesion -> GestorSesionUsuario : activarOpcionCerrarSesion()
deactivate VistaOpcionCerrarSesion
activate GestorSesionUsuario
GestorSesionUsuario -> SesionUsuario : realizarCierreDeSesion()
activate SesionUsuario
SesionUsuario -> SesionUsuario : actualizarHoraDeFin()
SesionUsuario -> GestorSesionUsuario : esExitoso()
deactivate SesionUsuario
GestorSesionUsuario -> VistaFormularioInicioSesion : mostrarFormularioDeInicio()
deactivate GestorSesionUsuario
activate VistaFormularioInicioSesion
deactivate VistaFormularioInicioSesion

@enduml
