@startuml DiagramaDeSecuenciaCerrarSesion
skinparam sequenceParticipant underline

actor Usuario as user
boundary VistaOpcionCerrarSesion
control GestorSesionUsuario
entity SesionUsuario
boundary VistaFormularioInicioSesion


user -> VistaOpcionCerrarSesion : 1:cerrarSesion()
activate VistaOpcionCerrarSesion
VistaOpcionCerrarSesion -> GestorSesionUsuario : 2:cerrarSesion(userId)
deactivate VistaOpcionCerrarSesion
activate GestorSesionUsuario
GestorSesionUsuario -> SesionUsuario : 3:cerrarSesion(userId)
activate SesionUsuario
SesionUsuario -> SesionUsuario : 4:actualizarHoraDeFin()
SesionUsuario --> GestorSesionUsuario : 5:esExitoso()
deactivate SesionUsuario
GestorSesionUsuario -> VistaFormularioInicioSesion : 6:mostrarFormularioDeInicio()
deactivate GestorSesionUsuario
activate VistaFormularioInicioSesion
deactivate VistaFormularioInicioSesion

@enduml
