@startuml DiagramaDeSecuenciaRegistrarRecaudos

actor Proponente
boundary VistaFormularioRegistroRecaudos
control GestorRecaudos
entity SesionUsuario
boundary VistaError
boundary VistaFormularioCargaCurso

Proponente -> VistaFormularioRegistroRecaudos : 1:registrarDatosRecaudos()
activate VistaFormularioRegistroRecaudos
VistaFormularioRegistroRecaudos -> VistaFormularioRegistroRecaudos : 2:esDatosRecaudosCompletos()
alt False
VistaFormularioRegistroRecaudos -> VistaError : 3:mostrarError()
end
VistaFormularioRegistroRecaudos -> GestorRecaudos : 3:registrarRecaudos()
deactivate VistaFormularioRegistroRecaudos
activate GestorRecaudos
activate SesionUsuario
GestorRecaudos -> SesionUsuario : 4:guardarDatos(datos, userId)
SesionUsuario -> SesionUsuario : 5:actualizarDatos(datos, userId)
SesionUsuario --> GestorRecaudos : 6:esExitoso()
deactivate SesionUsuario
deactivate GestorRecaudos
GestorRecaudos -> VistaFormularioCargaCurso : 7:mostrarCargaFormulacion(datos)
@enduml