@startuml DiagramaDeSecuenciaIniciarSesion
skinparam sequenceParticipant underline

actor Usuario as user
boundary VistaFormularioInicioSesion
control GestorSesionUsuario
entity SesionUsuario
boundary VistaDashboard
boundary VistaError


user -> VistaFormularioInicioSesion : 1:iniciarSesion()
activate VistaFormularioInicioSesion
user -> VistaFormularioInicioSesion : 2:ingresarDatos()
VistaFormularioInicioSesion -> GestorSesionUsuario : 3:iniciarSesion()
deactivate VistaFormularioInicioSesion
activate GestorSesionUsuario
GestorSesionUsuario -> SesionUsuario : 4:verficarDatos()
activate SesionUsuario
SesionUsuario -> SesionUsuario : 5:esCorrecto()
SesionUsuario -> SesionUsuario : 6:actualizarHoraDeInicio()
SesionUsuario --> GestorSesionUsuario : 7:responderValidacion()
deactivate SesionUsuario
alt True
GestorSesionUsuario -> VistaDashboard : 8:mostrarDashboard()
else False
GestorSesionUsuario -> VistaError : 8:mostrarError()
end
deactivate GestorSesionUsuario
activate VistaDashboard
deactivate VistaDashboard

@enduml
