@startuml DiagramaDeSecuenciaRegistrarse
skinparam sequenceParticipant underline

actor Usuario as user
boundary VistaFormularioRegistro
control GestorSesionUsuario
entity SesionUsuario
boundary VistaDashboard


user -> VistaFormularioRegistro : Registrarse()
activate VistaFormularioRegistro
user -> VistaFormularioRegistro : IngresarDatos()
VistaFormularioRegistro -> VistaFormularioRegistro : esDatosCompletos()
VistaFormularioRegistro -> GestorSesionUsuario : enviarDatos()
deactivate VistaFormularioRegistro
activate GestorSesionUsuario
GestorSesionUsuario -> SesionUsuario : registrarUsuario()
activate SesionUsuario
SesionUsuario -> SesionUsuario : CrearUsuario()
SesionUsuario -> SesionUsuario :  actualizarHoraDeInicio()
SesionUsuario --> GestorSesionUsuario : esExitosa()
deactivate SesionUsuario
GestorSesionUsuario -> VistaDashboard : mostrarDashboard()
deactivate GestorSesionUsuario
activate VistaDashboard
deactivate VistaDashboard


@enduml