@startuml DiagramaDeEstadoRelacionAdministrador
title Administrador

[*] --> UsuarioIniciado : iniciar sesión
UsuarioIniciado --> ViendoDashboardAdministrador : ver dashboard
ViendoDashboardAdministrador --> ViendoPropuestas : ver propuestas
ViendoPropuestas --> EvaluacionDeAvalRespondida : responder evaluación de aval
EvaluacionDeAvalRespondida --> ViendoDashboardAdministrador : regresar
ViendoPropuestas --> CartaDeIntencionFirmada : firmar carta de intención
CartaDeIntencionFirmada --> ViendoDashboardAdministrador : regresar
ViendoPropuestas --> CartaDeCompromisoGenerada : generar carta de compromiso
CartaDeCompromisoGenerada --> ViendoDashboardAdministrador : regresar
ViendoDashboardAdministrador ---> SesionCerrada : cerrar sesión 
SesionCerrada --> [*]

@enduml