@startuml DiagramaDePaquetes
left to right direction

' package "gestionDeCursos" as G_cursos{
'     object CursoDeExtension
' } 

package "gestionDeCursosPropuestos" as G_cursosPropuestos{
    object VerCursosPropuestos
    object VerEstadoDeAval
    object VerExpediente
}

package "gestionDeProcesoPropuesta" as G_propuesta{
    object RegistrarRecaudos
    object CargarFormulacionDelCursoDeExtension
}

package "gestionDePresentacionesDeCurso" as G_presentaciones{
    object PresentarCronogramaDeEjecucion
    object PresentarEstructuraDeCostosEIngreso
}

package "gestionDeAval" as G_aval{
    object EvaluarInformacionConsignada
    object ResponderEvaluacionDeAval
}

package "gestionDeCartasDePropuesta" as G_cartas{
    object GenerarCartaDeCompromiso
    object FirmarCartaDeIntencion
}


package "gestionDeSesionUsuario" as G_user {
    object Registrarse
    object IniciarSesion
    object CerrarSesion
    object VerDashboard
}

G_cursosPropuestos -d-> G_user #Black;line.dashed;
' G_cursosPropuestos --> G_cursos #Black;line.dashed;


G_presentaciones -d-> G_cursosPropuestos #Black;line.dashed;
G_aval -d-> G_cursosPropuestos #Black;line.dashed;
G_propuesta -d-> G_cursosPropuestos #Black;line.dashed;
G_cartas -d-> G_propuesta #Black;line.dashed;
' G_aval --> G_user #Black;line.dashed;
' G_cursosPropuestos ----> G_user #Black;line.dashed;
' G_propuesta ------> G_user #Black;line.dashed;

@enduml