@startuml DiagramaDeClaseResponderEvaluacion
left to right direction

actor "Administrador" as actorAdmin

entity "Propuesta" as entidadPropuesta
entity "Aval tecnico" as entidadAval

boundary "Vista de evaluacion" as vistaEvaluacion
boundary "Vista de informacion consignada" as vistaInfoConsignada
boundary "Vista de observaciones" as vistaObservaciones

control "Gestor de evaluacion" as ctrlGestorEvaluacion

actorAdmin -- vistaEvaluacion
vistaEvaluacion -- vistaInfoConsignada
vistaEvaluacion -- vistaObservaciones

vistaInfoConsignada -- entidadPropuesta

vistaEvaluacion -- ctrlGestorEvaluacion
entidadPropuesta -- entidadAval
ctrlGestorEvaluacion -- entidadAval

@enduml