@startuml DiagramaDeDespliegue

node "Cliente" as client {
  node "Usuario" {
  }
  node "Administrador" {
  }
}

node "Cliente Web" as webClient {
  
}

node "Cliente Movil" as mobileClient {
  
}

node "Servidor de Aplicaciones" as appServer {
  node "gestionDeCartasDePropuesta" {
    ' [GenerarCartaDeCompromiso]
    ' [FirmarCartaDeIntencion]
  }
  
  node "gestionDeProcesoPropuesta" {
    ' [RegistrarRecaudos]
    ' [CargarFormulacionDelCursoDeExtension]
  }

  node "gestionDeAval" {
    ' [EvaluarInformacionConsignada]
    ' [ResponderEvaluacionDeAval]
  }

  node "gestionDeSesionUsuario" {
    ' [IniciarSesion]
    ' [Registrarse]
    ' [VerDashboard]
    ' [CerrarSesion]
  }

  node "gestionDePresentacionesDeCurso" {
    ' [PresentarCronogramaDeEjecucion]
    ' [PresentarEstructuraDeCostosEIngreso]
  }

  node "gestionDeCursosPropuestos" {
    ' [VerEstadoDeAval]
    ' [VerCursosPropuestos]
    ' [VerExpediente]
  }
}

node "Base de Datos" as db {
  ' node "CourseManagerUCV" {
  ' }
}
webClient --|> client
mobileClient --|> client
client -d-- appServer : HTTP
appServer -d-- db

@enduml