@startuml DiagramaDeColaboracionDeDashboarAdministrador

:Administrador: as administrador


control "carta de intencion" as firmar
control "evaluacion Aval" as responder
control "generacion carta de compromiso" as Generar

boundary "Dashboard" as dashboard
entity "Firmar carta de intencion" as carta
entity "Responder evaluacion aval" as aval
entity "carta de compromiso" as carta_compromiso



administrador --> dashboard: "VeDashboard()"
dashboard --> firmar : "IniciaGenerarCartaDeIntencion()"
dashboard ---> responder : "IniciarResponderEvaluacion()"
dashboard--> Generar : "IniciarGenerarCartaDeCompromiso()"

firmar--> carta : "AccedeFirmarCarta()"
responder --> aval : "AccedeResponderEvaluacionAval()"
Generar --> carta_compromiso : "AccedeCartaDeCompromiso"






@enduml