@startuml DisciplinaDeAnalisisDiagramaDeClaseFirmarCartaIntencion
left to right direction

actor "Administrador" as actorAdmin

entity "Propuesta" as entidadPropuesta
entity "Aval tecnico" as entidadAval
entity "Expediente" as entidadExpediente
entity "Carta de intencion" as entidadCartaIntencion

boundary "Vista de propuestas" as vistaPropuestas
boundary "Vista de generar carta de intencion" as vistaGenerarCartaIntencion
boundary "Vista de ingresar informacion" as vistaIngresarInformacion

control "Gestor de carta de intencion" as ctrlGestorCartaIntencion

actorAdmin -- vistaPropuestas
vistaPropuestas -- entidadPropuesta
vistaPropuestas -- vistaGenerarCartaIntencion
vistaGenerarCartaIntencion -- ctrlGestorCartaIntencion

vistaGenerarCartaIntencion -- vistaIngresarInformacion
ctrlGestorCartaIntencion -- entidadCartaIntencion 
entidadCartaIntencion -- entidadExpediente
ctrlGestorCartaIntencion -- entidadAval

@enduml