@startuml DiagramaDeColaboracionDeDasboardProponente

:Proponente: as Propoonente

boundary "opcion ver dashboard" as ver
control "Apertura dashboard" as verificacion

control "expediente" as expediente
control "cursos propuestos" as cursos
control "Registro recaudos" as registrar

boundary "Dashboard" as dashboard

entity "Ver expediente" as ver_expediente
entity "Ver cursos propuestos" as ver_cursos
entity "Registrar recaudos" as recaudos



Propoonente-> ver: "SolicitarVerdashboard()"
ver--> verificacion: "AbrirDashboard()"
verificacion --> dashboard: "MostrarDashboard()"
dashboard --> expediente : "IniciarVerExpediente()"
dashboard --> registrar : "IniciarRegistrarRecaudos()"
dashboard --> cursos : "iniciarCursosPropuestos()"

expediente --> ver_expediente : "AccedeExpediente()"
cursos --> ver_cursos  : "MostrarCursosPropuestos()"
registrar --> recaudos : "AccedeRegistrarRecaudos()"